apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopping-ingress
  namespace: shopping-planning
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: shopping.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shopping-svc
                port:
                  number: 80
